### ISSUE TITLE
Are there any special steps to uninstalling Cephytools?

### ISSUE THREAD

**Issue by sylvesterroos** [elluzion/cephytools#1]
I want to return the function of the AI button to whatever my ROM's default setting was. Are there any special steps required before I uninstall Cephytools?

**Comment by elluzion** [comment]
There are no steps required directly, but I can add a function to restore the original behavior of the button. When using the app, it creates a backup file in system/usr/keylayout/gpio-keys.kl.bak.
To manually restore the default behavior, you can also replace gpio-keys.kl with gpio-keys.kl.bak again

**Comment by sylvesterroos** [comment]
That would be a great QoL improvement 👍
In the meantime I've simply replaced the file as you explained
